### ISSUE TITLE
Export-IdentityNowConfig throwing error when providing directory path

### ISSUE THREAD

**Issue by bama19942000** [darrenjrobinson/powershell_module_identitynow#40] opened 2021-06-22 14:19 UTC
Export-IdentityNowConfig -path 'c:\test' -Items Rules,Roles
Export-IdentityNowConfig : provided path is not a directory: c:\test
At line:1 char:1
+ Export-IdentityNowConfig -path 'c:\test' -Items Rules,Roles
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-IdentityNowConfig

Tried it multiple times and multiple ways

**Comment by darrenjrobinson** [comment] 2021-06-22 20:39
What version of PowerShell are you using? Does the c:\test directory exist and the logged in user account have access?

![image](https://user-images.githubusercontent.com/384733/122995773-5ca59f00-d3ed-11eb-81c1-6b599a441ea0.png)

![image](https://user-images.githubusercontent.com/384733/122995982-a68e8500-d3ed-11eb-9555-201613a040a8.png)

**Comment by bama19942000** [comment] 2021-06-23 13:12
PS C:\WINDOWS\system32>  Get-Host | Select-Object Version

Version      
-------      
5.1.17134.858



PS C:\WINDOWS\system32> Export-IdentityNowConfig -path 'C:\scratchdump' -Items IdentityProfiles
Export-IdentityNowConfig : provided path is not a directory: C:\scratchdump
At line:1 char:1
+ Export-IdentityNowConfig -path 'C:\scratchdump' -Items IdentityProfil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-IdentityNowConfig

I am running PS as an administrator and can intellisense to the various paths I set up. I also completely uninstalled the module and reinstalled.

**Comment by bama19942000** [comment] 2021-06-23 13:33
Export-IdentityNowConfig : provided path is not a directory: C:\scratchdump
At line:1 char:1
+ Export-IdentityNowConfig -path 'C:\scratchdump' -Items IdentityProfil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-IdentityNowConfig

**Comment by bama19942000** [comment] 2021-06-23 14:19
Darren, I had a coworker try this with the same results.

**Comment by darrenjrobinson** [comment] 2021-06-23 21:47
Thanks @bama19942000 
I've been able to recreate the issue using PowerShell 5.1.
The problem is with PowerShell 5.1 and the different way System.IO functions. 

I've written and tested an update using both PS 5.1 and PS7.x 
It is under a new branch v1.1.5 https://github.com/darrenjrobinson/powershell_module_identitynow/tree/v1.1.5
You can download that individual script for the module from here https://github.com/darrenjrobinson/powershell_module_identitynow/blob/v1.1.5/scripts/Export-IdentityNowConfig.ps1 

Let me know how you go in your environment.

**Comment by bama19942000** [comment] 2021-06-24 17:14
Thank you, Darren! It works.

**Comment by darrenjrobinson** [comment] 2021-06-25 01:58
Fantastic. 
I'll close this and look to release v1.1.5 once I've looked at the other enhancement and anything else that pops up..

**Closed as completed** 2021-07-08 00:23 UTC
Labels: question
